#!/bin/sh

# Copyright: (C) 2017-2018, Stefan Lippers-Hollmann <s.l-h@gmx.de>

# License: ISC
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -e

usage() {
	cat <<EOF
$(basename $0): parse and set the dual boot configuration on the ZyXEL NBG6817

Parameters:
-h|--help               this usage information
--check-mtd-integrity   check the integrity of the dualflag mtd
--get-mtd               get the dualflag mtd
                        /dev/mtdblock6 (ZyXEL OEM) or /dev/mtdblock11 (LEDE)
--get-rootfs            get the currently configured rootfs
                        /dev/mmcblk0p5 or /dev/mmcblk0p8
--get-version <blkdev>  try to decode the version of the firmware installed in
                        the named rootfs (/dev/mmcblk0p5 or /dev/mmcblk0p8)
-l|--list               list installed firmwares
--set-rootfs <blkdev>   set the desired rootfs
                        /dev/mmcblk0p5 or /dev/mmcblk0p8

EOF
}

get_mtd() {
	local DUAL_FLAG_MTD

	# LEDE uses "0:DUAL_FLAG" (/dev/mtdblock11)
	DUAL_FLAG_MTD="$(find_mtd_part 0:DUAL_FLAG)"
	if [ -z "${DUAL_FLAG_MTD}" ]; then
		# the ZyXEL OEM firmware uses "dualflag" (/dev/mtdblock6)
		DUAL_FLAG_MTD="$(find_mtd_part dualflag)"
	fi

	# check that the detected mtd is really a block device
	if [ -b "${DUAL_FLAG_MTD}" ]; then
		echo $DUAL_FLAG_MTD
	else
		echo "ERROR: failing to find DUAL_FLAG mtd" >&2
		exit 1
	fi
}

get_rootfs() {
	local BOOT_FLAG

	BOOT_FLAG=$(dd if=$(get_mtd) bs=1 count=1 2>/dev/null | hexdump -n 1 -e '1/1 "%02x\n"')
	if [ "0x${BOOT_FLAG}" = "0xff" ]; then
		# using header (mmcblk0p3)/ kernel (mmcblk0p4)/ rootfs (mmcblk0p5)
		echo "/dev/mmcblk0p5"
	elif [ "0x${BOOT_FLAG}" = "0x01" ]; then
		# using header_1 (mmcblk0p6)/ kernel_1 (mmcblk0p7)/ rootfs_1 (mmcblk0p8)
		echo "/dev/mmcblk0p8"
	else
		echo "ERROR: can't parse bootflag"
		exit 2
	fi
}

get_version() {
	local HEADER
	local KERNEL
	local ROOTFS
	local ALTBOOT
	ROOTFS="$1"

	case "$ROOTFS" in
		/dev/mmcblk0p5)
			HEADER=/dev/mmcblk0p3
			KERNEL=/dev/mmcblk0p4
			ALTBOOT=""
			;;
		/dev/mmcblk0p8)
			HEADER=/dev/mmcblk0p6
			KERNEL=/dev/mmcblk0p7
			ALTBOOT="_1"
			;;
		*)
			echo "ERROR: invalid rootfs supplied." >&2
			exit 13
			;;
	esac

	FIRMWARE_VERSION="$(dd if=${HEADER} bs=1 skip=8 count=16 2>/dev/null)"
	KERNEL_VERSION="$(dd if=${KERNEL} bs=1 skip=32 count=25 2>/dev/null)"

	case "$KERNEL_VERSION" in
		ARM*Linux-*)
			# LEDE/ OpenWrt
			FIRMWARE_VERSION="LEDE/ Openwrt <unknown revision>"
			;;
		Linux-*)
			# ZyXEL OEM firmware
			:
			;;
		*)
			echo "ERROR: version of the installed firmware can't be decoded." >&2
			exit 12
			;;
	esac

	cat <<EOF
"header${ALTBOOT}" partition is located at "${HEADER}"
"kernel${ALTBOOT}" partition is located at "${KERNEL}"
"rootfs${ALTBOOT}" partition is located at "${ROOTFS}"

FIRMWARE_VERSION="${FIRMWARE_VERSION}"
KERNEL_VERSION="${KERNEL_VERSION}"
UNAME_VERSION="${KERNEL_VERSION##*Linux-}"
EOF
}

set_rootfs() {
	local ROOTFS
	ROOTFS="$1"

	if [ -z "${ROOTFS}" ] || [ ! -b "${ROOTFS}" ]; then
		echo "ERROR: provided rootfs (${ROOTFS}) not a block device" >&2
		exit 3
	fi

	case "$ROOTFS" in
		/dev/mmcblk0p5)
			printf "\xff" >$(get_mtd)
			;;
		/dev/mmcblk0p8)
			printf "\x01" >$(get_mtd)
			;;
		*)
			echo "ERROR: invalid rootfs (${ROOTFS})" >&2
			exit 4
			;;
	esac
}

check_mtd_integrity() {
	local MTD_CHECKSUM

	# use md5 as checksum algorithm, sha256 is not supported by the
	# ZyXEL OEM firmware.
	MTD_CHECKSUM="$(md5sum $(get_mtd) | awk '{print $1}')"

	case $MTD_CHECKSUM in
		ecb99e6ffea7be1e5419350f725da86b)
			echo "valid dualflag signature found (0xFF, /dev/mmcblk0p5)."
			;;
		e107d3d780e73f0b5c7d48ec749e66f9)
			echo "valid dualflag signature found (0x01, /dev/mmcblk0p8)."
			;;
		*)
			echo "ERROR: unrecognized dualflag signature."
			exit 5
			;;
	esac
}

# ugly workaround, the OEM firmware doesn't define this function, while still
# providing and populating /tmp/sysinfo/board_name correctly, let this be
# redefined by /lib/functions.sh on LEDE
board_name() {
	[ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

# provide find_mtd_part(), available in both LEDE and the ZyXEL OEM firmware
if [ -r /lib/functions.sh ]; then
	. /lib/functions.sh
else
	echo "ERROR: this tool can only be used on OpenWrt or the ZyXEL NBG6817 OEM firmware." >&2
	exit 6
fi

# bail out screaming, if this gets not executed on a ZyXEL NBG6817
case "$(board_name)" in
	zyxel,nbg6817|nbg6817)
		:
		;;
	*)
		echo "ERROR: this tool is only safe to be used on the ZyXEL NBG6817" >&2
		exit 7
		;;
esac

# at least one parameter is required
if [ -z "${1}" ]; then
	usage
	exit 8
fi

case "$1" in
	-h|--help)
		usage
		exit 0
		;;
	--check-mtd-integrity)
		echo $(check_mtd_integrity)
		exit 0
		;;
	--get-mtd)
		echo $(get_mtd)
		exit 0
		;;
	--get-rootfs)
		echo $(get_rootfs)
		exit 0
		;;
	--get-version)
		if [ -n "$2" ]; then
			get_version "$2"
		else
			echo "ERROR: rootfs not provided" >&2
			usage
			exit 11
		fi
		exit 0
		;;
	-l|--list)
		"${0}" --get-version /dev/mmcblk0p5
		echo ""
		echo ""
		"${0}" --get-version /dev/mmcblk0p8
		exit 0
		;;
	--set-rootfs)
		if [ -n "$2" ]; then
			set_rootfs "$2"
		else
			echo "ERROR: rootfs not provided" >&2
			usage
			exit 9
		fi
		exit 0
		;;
	*)
		usage
		exit 10
		;;
esac

